### ISSUE TITLE
Unity Record Overlay Canvas?

### ISSUE THREAD

**Issue by SabreRunner** [olokobayusuf/NatCorder-Docs#2]
I found no other place to raise issues regarding NatCorder so I'm doing it here.
My company bought the Unity asset for use in our applications. I'm trying to use it to record from an AR application but it's not getting the canvas. Obviously, it's recording from the camera and the UI is an overlay.
Is there any way to capture the UI too and integrate it into the video? No, I can't change the UI to camera space. It conflicts with the AR engine and causes weird bugs.

**Comment by olokobayusuf** [comment]
You can [email me directly](mailto:olokobayusuf@gmail.com) for NatCorder issues.
> No, I can't change the UI to camera space. It conflicts with the AR engine and causes weird bugs.

I'm guessing you might have noticed I mentioned that Overlay canvases don't work with NatCorder. There is no way to use Overlay canvases with NatCorder. This is [by design](https://issuetracker.unity3d.com/issues/rendertextures-do-not-include-canvas-ui-elements), [by Unity](https://forum.unity.com/threads/render-a-canvas-to-rendertexture.272754/#post-1804847).
